name: publish

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: Ubuntu-20.04
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Echo
        run: echo ${{ steps.get_version.outputs.VERSION }}
