name: publish

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Extract version tag
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: |
            krystian19/czar:latest
            krystian19/czar:${{ steps.get_version.outputs.VERSION }}
