name: release

on:
  push:
    branches: [ main ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: "15.x"
      - run: yarn install
      - run: yarn build
      - run: npx semantic-release
        # env:
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}